# Generated by Django 4.2 on 2024-10-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_options_remove_booking_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
