# Generated by Django 4.2 on 2024-10-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_created_at_booking_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
