# Generated by Django 4.2 on 2024-10-25 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0003_rename_time_talk_start_time_talk_end_time'),
        ('bookings', '0009_remove_booking_talk_alter_booking_speaker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talks.talk'),
        ),
    ]
