# Generated by Django 4.2 on 2024-10-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_booking_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
