# Generated by Django 4.2 on 2024-11-01 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0003_rename_time_talk_start_time_talk_end_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0011_alter_booking_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='talk',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='talks.talk'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('owner', 'talk')},
        ),
    ]
